# comment to fire up github actions 2
name: "Telomare CI"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v13
      with:
        # nix_path: nixpkgs=channel:nixos-unstable
        # skip_adding_nixpkgs_channel: true
        install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v10
      with:
        name: telomare
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build and test
      run: |
        echo cachix use iohk
        cachix use iohk
        echo nix build
        nix build .#telomare:exe:telomare
        echo nix run tests
        nix run .#telomare:test:telomare-test
        nix run .#telomare:test:telomare-parser-test
        nix run .#telomare:test:telomare-serializer-test
        echo testing telomare-mini-repl
        [[ "8" -eq $(nix develop -c cabal run telomare-mini-repl -- --expr 'succ 7' | tail -n 1) ]]
        echo building for legacy nix-shell
        nix-build
        nix-shell --run "echo OK"
        echo ${{ github.ref }}
        echo ${{ github.repository }}
  format:
    if: ${{ (github.ref == 'refs/heads/master') && (github.repository == 'Stand-In-Language/stand-in-language') }}
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout telomare repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          repository: Stand-In-Language/stand-in-language
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: telomare
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: stylish-haskell formatting
        run: |
          ls
          nix develop -c stylish-haskell -irv .
          echo stylish-haskell formatting finished
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'stylish-haskell formatting automatically applied'
          default_author: github_actions
  release:
    if: ${{ (github.ref == 'refs/heads/master') && (github.repository == 'Stand-In-Language/stand-in-language') }}
    needs: [tests, format]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout telomare repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          repository: Stand-In-Language/stand-in-language
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: ./telomare
      - name: Checkout telomare site repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          repository: Stand-In-Language/stand-in-language.github.io
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: ./stand-in-language.github.io
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: telomare
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: haddock build
        run: |
          ls
          cd telomare
          nix develop -c cabal haddock --haddock-hyperlink-source
          echo OK Haddock build
      - name: haddock copy
        run: |
          ls
          rm -rf stand-in-language.github.io/docs/haddock/
          mkdir stand-in-language.github.io/docs/haddock/
          cp -r telomare/dist-newstyle/build/x86_64-linux/ghc-8.8.4/telomare-0.1.0.0/doc/html/telomare/. stand-in-language.github.io/docs/haddock
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'haddock documentation automatically updated'
          cwd: './stand-in-language.github.io/'
          default_author: github_actions
