name: "Telomare CI"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2.3.4
    - uses: actions/checkout@v2
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        # nix_path: nixpkgs=channel:nixos-unstable
        # skip_adding_nixpkgs_channel: true
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v8
      with:
        name: telomare
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build and test
      run: |
        cachix use iohk
        nix build .#telomare:exe:telomare
        nix run .#telomare:test:telomare-test
        nix run .#telomare:test:telomare-parser-test
        nix run .#telomare:test:telomare-serializer-test
        echo ${{ github.ref }}
        echo ${{ github.repository }}

  format:
    if: ${{ (github.repository == 'hhefesto/stand-in-language') }}
    # TODO: remove the above use the below comment
    # if: ${{ (github.ref == 'refs/heads/master') && (github.repository == 'Stand-In-Language/stand-in-language') }}
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout telomare repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: Stand-In-Language/stand-in-language
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: ./telomare
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v8
        with:
          name: telomare
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: stylish-haskell formatting
        run: |
          ls
          nix develop -c stylish-haskell -ir telomare
          echo stylish-haskell formatting finished
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'stylish-haskell formatting automatically applied'
          cwd: './stand-in-language.github.io/'
          default_author: github_actions

  release:
    if: ${{ (github.ref == 'refs/heads/master') && (github.repository == 'Stand-In-Language/stand-in-language') }}
    needs: tests format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout telomare repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: Stand-In-Language/stand-in-language
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: ./telomare
      - name: Checkout telomare site repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: Stand-In-Language/stand-in-language.github.io
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: ./stand-in-language.github.io
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v8
        with:
          name: telomare
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: haddock build
        run: |
          ls
          cd telomare
          nix run .#haddockScript
          echo OK Haddock build
      - name: haddock copy
        run: |
          ls
          rm -rf stand-in-language.github.io/docs/haddock/
          mkdir stand-in-language.github.io/docs/haddock/
          cp -r telomare/dist-newstyle/build/x86_64-linux/ghc-8.8.4/telomare-0.1.0.0/doc/html/telomare/. stand-in-language.github.io/docs/haddock
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'haddock documentation automatically updated'
          cwd: './stand-in-language.github.io/'
          default_author: github_actions
